name: Go Build
on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Go vet
      run: go vet

    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1


    - name: Build
      run: make all

